CLASS LHC_SUPPLIERINVITM DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEITEMID FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  SupplierInvItm~CalculateItemID .
ENDCLASS.

CLASS LHC_SUPPLIERINVITM IMPLEMENTATION.
  METHOD CALCULATEITEMID.
  ENDMETHOD.
ENDCLASS.
